// GENERATED FILE — do not edit by hand.
//
// Dial codes come from libphonenumber-js metadata and country names from
// Node's Intl.DisplayNames, both captured at generation time. Baking the
// names in rather than calling Intl.DisplayNames at runtime keeps the
// rendered markup byte-identical on server and client: Node and the browser
// can ship different CLDR versions, and a name that disagreed between them
// would surface as a hydration mismatch across a 245-option list.
//
// libphonenumber-js is NOT a dependency of this project — it was used once,
// outside the repo, to produce this file.

export type Country = {
  /** ISO 3166-1 alpha-2, also the <option> value. */
  code: string;
  /** Calling code without the leading "+". */
  dial: string;
  en: string;
  fr: string;
};

/** Primary audience of these pages. */
export const DEFAULT_COUNTRY_CODE = "CM";

/** Sorted by English name. */
export const COUNTRIES: Country[] = [
  { code: "AF", dial: "93", en: "Afghanistan", fr: "Afghanistan" },
  { code: "AX", dial: "358", en: "Åland Islands", fr: "Îles Åland" },
  { code: "AL", dial: "355", en: "Albania", fr: "Albanie" },
  { code: "DZ", dial: "213", en: "Algeria", fr: "Algérie" },
  { code: "AS", dial: "1", en: "American Samoa", fr: "Samoa américaines" },
  { code: "AD", dial: "376", en: "Andorra", fr: "Andorre" },
  { code: "AO", dial: "244", en: "Angola", fr: "Angola" },
  { code: "AI", dial: "1", en: "Anguilla", fr: "Anguilla" },
  { code: "AG", dial: "1", en: "Antigua & Barbuda", fr: "Antigua-et-Barbuda" },
  { code: "AR", dial: "54", en: "Argentina", fr: "Argentine" },
  { code: "AM", dial: "374", en: "Armenia", fr: "Arménie" },
  { code: "AW", dial: "297", en: "Aruba", fr: "Aruba" },
  { code: "AC", dial: "247", en: "Ascension Island", fr: "Île de l’Ascension" },
  { code: "AU", dial: "61", en: "Australia", fr: "Australie" },
  { code: "AT", dial: "43", en: "Austria", fr: "Autriche" },
  { code: "AZ", dial: "994", en: "Azerbaijan", fr: "Azerbaïdjan" },
  { code: "BS", dial: "1", en: "Bahamas", fr: "Bahamas" },
  { code: "BH", dial: "973", en: "Bahrain", fr: "Bahreïn" },
  { code: "BD", dial: "880", en: "Bangladesh", fr: "Bangladesh" },
  { code: "BB", dial: "1", en: "Barbados", fr: "Barbade" },
  { code: "BY", dial: "375", en: "Belarus", fr: "Biélorussie" },
  { code: "BE", dial: "32", en: "Belgium", fr: "Belgique" },
  { code: "BZ", dial: "501", en: "Belize", fr: "Belize" },
  { code: "BJ", dial: "229", en: "Benin", fr: "Bénin" },
  { code: "BM", dial: "1", en: "Bermuda", fr: "Bermudes" },
  { code: "BT", dial: "975", en: "Bhutan", fr: "Bhoutan" },
  { code: "BO", dial: "591", en: "Bolivia", fr: "Bolivie" },
  { code: "BA", dial: "387", en: "Bosnia & Herzegovina", fr: "Bosnie-Herzégovine" },
  { code: "BW", dial: "267", en: "Botswana", fr: "Botswana" },
  { code: "BR", dial: "55", en: "Brazil", fr: "Brésil" },
  { code: "IO", dial: "246", en: "British Indian Ocean Territory", fr: "Territoire britannique de l’océan Indien" },
  { code: "VG", dial: "1", en: "British Virgin Islands", fr: "Îles Vierges britanniques" },
  { code: "BN", dial: "673", en: "Brunei", fr: "Brunei" },
  { code: "BG", dial: "359", en: "Bulgaria", fr: "Bulgarie" },
  { code: "BF", dial: "226", en: "Burkina Faso", fr: "Burkina Faso" },
  { code: "BI", dial: "257", en: "Burundi", fr: "Burundi" },
  { code: "KH", dial: "855", en: "Cambodia", fr: "Cambodge" },
  { code: "CM", dial: "237", en: "Cameroon", fr: "Cameroun" },
  { code: "CA", dial: "1", en: "Canada", fr: "Canada" },
  { code: "CV", dial: "238", en: "Cape Verde", fr: "Cap-Vert" },
  { code: "BQ", dial: "599", en: "Caribbean Netherlands", fr: "Pays-Bas caribéens" },
  { code: "KY", dial: "1", en: "Cayman Islands", fr: "Îles Caïmans" },
  { code: "CF", dial: "236", en: "Central African Republic", fr: "République centrafricaine" },
  { code: "TD", dial: "235", en: "Chad", fr: "Tchad" },
  { code: "CL", dial: "56", en: "Chile", fr: "Chili" },
  { code: "CN", dial: "86", en: "China", fr: "Chine" },
  { code: "CX", dial: "61", en: "Christmas Island", fr: "Île Christmas" },
  { code: "CC", dial: "61", en: "Cocos (Keeling) Islands", fr: "Îles Cocos" },
  { code: "CO", dial: "57", en: "Colombia", fr: "Colombie" },
  { code: "KM", dial: "269", en: "Comoros", fr: "Comores" },
  { code: "CG", dial: "242", en: "Congo - Brazzaville", fr: "Congo-Brazzaville" },
  { code: "CD", dial: "243", en: "Congo - Kinshasa", fr: "Congo-Kinshasa" },
  { code: "CK", dial: "682", en: "Cook Islands", fr: "Îles Cook" },
  { code: "CR", dial: "506", en: "Costa Rica", fr: "Costa Rica" },
  { code: "CI", dial: "225", en: "Côte d’Ivoire", fr: "Côte d’Ivoire" },
  { code: "HR", dial: "385", en: "Croatia", fr: "Croatie" },
  { code: "CU", dial: "53", en: "Cuba", fr: "Cuba" },
  { code: "CW", dial: "599", en: "Curaçao", fr: "Curaçao" },
  { code: "CY", dial: "357", en: "Cyprus", fr: "Chypre" },
  { code: "CZ", dial: "420", en: "Czechia", fr: "Tchéquie" },
  { code: "DK", dial: "45", en: "Denmark", fr: "Danemark" },
  { code: "DJ", dial: "253", en: "Djibouti", fr: "Djibouti" },
  { code: "DM", dial: "1", en: "Dominica", fr: "Dominique" },
  { code: "DO", dial: "1", en: "Dominican Republic", fr: "République dominicaine" },
  { code: "EC", dial: "593", en: "Ecuador", fr: "Équateur" },
  { code: "EG", dial: "20", en: "Egypt", fr: "Égypte" },
  { code: "SV", dial: "503", en: "El Salvador", fr: "Salvador" },
  { code: "GQ", dial: "240", en: "Equatorial Guinea", fr: "Guinée équatoriale" },
  { code: "ER", dial: "291", en: "Eritrea", fr: "Érythrée" },
  { code: "EE", dial: "372", en: "Estonia", fr: "Estonie" },
  { code: "SZ", dial: "268", en: "Eswatini", fr: "Eswatini" },
  { code: "ET", dial: "251", en: "Ethiopia", fr: "Éthiopie" },
  { code: "FK", dial: "500", en: "Falkland Islands", fr: "Îles Malouines" },
  { code: "FO", dial: "298", en: "Faroe Islands", fr: "Îles Féroé" },
  { code: "FJ", dial: "679", en: "Fiji", fr: "Fidji" },
  { code: "FI", dial: "358", en: "Finland", fr: "Finlande" },
  { code: "FR", dial: "33", en: "France", fr: "France" },
  { code: "GF", dial: "594", en: "French Guiana", fr: "Guyane française" },
  { code: "PF", dial: "689", en: "French Polynesia", fr: "Polynésie française" },
  { code: "GA", dial: "241", en: "Gabon", fr: "Gabon" },
  { code: "GM", dial: "220", en: "Gambia", fr: "Gambie" },
  { code: "GE", dial: "995", en: "Georgia", fr: "Géorgie" },
  { code: "DE", dial: "49", en: "Germany", fr: "Allemagne" },
  { code: "GH", dial: "233", en: "Ghana", fr: "Ghana" },
  { code: "GI", dial: "350", en: "Gibraltar", fr: "Gibraltar" },
  { code: "GR", dial: "30", en: "Greece", fr: "Grèce" },
  { code: "GL", dial: "299", en: "Greenland", fr: "Groenland" },
  { code: "GD", dial: "1", en: "Grenada", fr: "Grenade" },
  { code: "GP", dial: "590", en: "Guadeloupe", fr: "Guadeloupe" },
  { code: "GU", dial: "1", en: "Guam", fr: "Guam" },
  { code: "GT", dial: "502", en: "Guatemala", fr: "Guatemala" },
  { code: "GG", dial: "44", en: "Guernsey", fr: "Guernesey" },
  { code: "GN", dial: "224", en: "Guinea", fr: "Guinée" },
  { code: "GW", dial: "245", en: "Guinea-Bissau", fr: "Guinée-Bissau" },
  { code: "GY", dial: "592", en: "Guyana", fr: "Guyana" },
  { code: "HT", dial: "509", en: "Haiti", fr: "Haïti" },
  { code: "HN", dial: "504", en: "Honduras", fr: "Honduras" },
  { code: "HK", dial: "852", en: "Hong Kong SAR China", fr: "R.A.S. chinoise de Hong Kong" },
  { code: "HU", dial: "36", en: "Hungary", fr: "Hongrie" },
  { code: "IS", dial: "354", en: "Iceland", fr: "Islande" },
  { code: "IN", dial: "91", en: "India", fr: "Inde" },
  { code: "ID", dial: "62", en: "Indonesia", fr: "Indonésie" },
  { code: "IR", dial: "98", en: "Iran", fr: "Iran" },
  { code: "IQ", dial: "964", en: "Iraq", fr: "Irak" },
  { code: "IE", dial: "353", en: "Ireland", fr: "Irlande" },
  { code: "IM", dial: "44", en: "Isle of Man", fr: "Île de Man" },
  { code: "IL", dial: "972", en: "Israel", fr: "Israël" },
  { code: "IT", dial: "39", en: "Italy", fr: "Italie" },
  { code: "JM", dial: "1", en: "Jamaica", fr: "Jamaïque" },
  { code: "JP", dial: "81", en: "Japan", fr: "Japon" },
  { code: "JE", dial: "44", en: "Jersey", fr: "Jersey" },
  { code: "JO", dial: "962", en: "Jordan", fr: "Jordanie" },
  { code: "KZ", dial: "7", en: "Kazakhstan", fr: "Kazakhstan" },
  { code: "KE", dial: "254", en: "Kenya", fr: "Kenya" },
  { code: "KI", dial: "686", en: "Kiribati", fr: "Kiribati" },
  { code: "XK", dial: "383", en: "Kosovo", fr: "Kosovo" },
  { code: "KW", dial: "965", en: "Kuwait", fr: "Koweït" },
  { code: "KG", dial: "996", en: "Kyrgyzstan", fr: "Kirghizstan" },
  { code: "LA", dial: "856", en: "Laos", fr: "Laos" },
  { code: "LV", dial: "371", en: "Latvia", fr: "Lettonie" },
  { code: "LB", dial: "961", en: "Lebanon", fr: "Liban" },
  { code: "LS", dial: "266", en: "Lesotho", fr: "Lesotho" },
  { code: "LR", dial: "231", en: "Liberia", fr: "Liberia" },
  { code: "LY", dial: "218", en: "Libya", fr: "Libye" },
  { code: "LI", dial: "423", en: "Liechtenstein", fr: "Liechtenstein" },
  { code: "LT", dial: "370", en: "Lithuania", fr: "Lituanie" },
  { code: "LU", dial: "352", en: "Luxembourg", fr: "Luxembourg" },
  { code: "MO", dial: "853", en: "Macao SAR China", fr: "R.A.S. chinoise de Macao" },
  { code: "MG", dial: "261", en: "Madagascar", fr: "Madagascar" },
  { code: "MW", dial: "265", en: "Malawi", fr: "Malawi" },
  { code: "MY", dial: "60", en: "Malaysia", fr: "Malaisie" },
  { code: "MV", dial: "960", en: "Maldives", fr: "Maldives" },
  { code: "ML", dial: "223", en: "Mali", fr: "Mali" },
  { code: "MT", dial: "356", en: "Malta", fr: "Malte" },
  { code: "MH", dial: "692", en: "Marshall Islands", fr: "Îles Marshall" },
  { code: "MQ", dial: "596", en: "Martinique", fr: "Martinique" },
  { code: "MR", dial: "222", en: "Mauritania", fr: "Mauritanie" },
  { code: "MU", dial: "230", en: "Mauritius", fr: "Maurice" },
  { code: "YT", dial: "262", en: "Mayotte", fr: "Mayotte" },
  { code: "MX", dial: "52", en: "Mexico", fr: "Mexique" },
  { code: "FM", dial: "691", en: "Micronesia", fr: "Micronésie" },
  { code: "MD", dial: "373", en: "Moldova", fr: "Moldavie" },
  { code: "MC", dial: "377", en: "Monaco", fr: "Monaco" },
  { code: "MN", dial: "976", en: "Mongolia", fr: "Mongolie" },
  { code: "ME", dial: "382", en: "Montenegro", fr: "Monténégro" },
  { code: "MS", dial: "1", en: "Montserrat", fr: "Montserrat" },
  { code: "MA", dial: "212", en: "Morocco", fr: "Maroc" },
  { code: "MZ", dial: "258", en: "Mozambique", fr: "Mozambique" },
  { code: "MM", dial: "95", en: "Myanmar (Burma)", fr: "Myanmar (Birmanie)" },
  { code: "NA", dial: "264", en: "Namibia", fr: "Namibie" },
  { code: "NR", dial: "674", en: "Nauru", fr: "Nauru" },
  { code: "NP", dial: "977", en: "Nepal", fr: "Népal" },
  { code: "NL", dial: "31", en: "Netherlands", fr: "Pays-Bas" },
  { code: "NC", dial: "687", en: "New Caledonia", fr: "Nouvelle-Calédonie" },
  { code: "NZ", dial: "64", en: "New Zealand", fr: "Nouvelle-Zélande" },
  { code: "NI", dial: "505", en: "Nicaragua", fr: "Nicaragua" },
  { code: "NE", dial: "227", en: "Niger", fr: "Niger" },
  { code: "NG", dial: "234", en: "Nigeria", fr: "Nigeria" },
  { code: "NU", dial: "683", en: "Niue", fr: "Niue" },
  { code: "NF", dial: "672", en: "Norfolk Island", fr: "Île Norfolk" },
  { code: "KP", dial: "850", en: "North Korea", fr: "Corée du Nord" },
  { code: "MK", dial: "389", en: "North Macedonia", fr: "Macédoine du Nord" },
  { code: "MP", dial: "1", en: "Northern Mariana Islands", fr: "Îles Mariannes du Nord" },
  { code: "NO", dial: "47", en: "Norway", fr: "Norvège" },
  { code: "OM", dial: "968", en: "Oman", fr: "Oman" },
  { code: "PK", dial: "92", en: "Pakistan", fr: "Pakistan" },
  { code: "PW", dial: "680", en: "Palau", fr: "Palaos" },
  { code: "PS", dial: "970", en: "Palestinian Territories", fr: "Territoires palestiniens" },
  { code: "PA", dial: "507", en: "Panama", fr: "Panama" },
  { code: "PG", dial: "675", en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", dial: "595", en: "Paraguay", fr: "Paraguay" },
  { code: "PE", dial: "51", en: "Peru", fr: "Pérou" },
  { code: "PH", dial: "63", en: "Philippines", fr: "Philippines" },
  { code: "PL", dial: "48", en: "Poland", fr: "Pologne" },
  { code: "PT", dial: "351", en: "Portugal", fr: "Portugal" },
  { code: "PR", dial: "1", en: "Puerto Rico", fr: "Porto Rico" },
  { code: "QA", dial: "974", en: "Qatar", fr: "Qatar" },
  { code: "RE", dial: "262", en: "Réunion", fr: "La Réunion" },
  { code: "RO", dial: "40", en: "Romania", fr: "Roumanie" },
  { code: "RU", dial: "7", en: "Russia", fr: "Russie" },
  { code: "RW", dial: "250", en: "Rwanda", fr: "Rwanda" },
  { code: "WS", dial: "685", en: "Samoa", fr: "Samoa" },
  { code: "SM", dial: "378", en: "San Marino", fr: "Saint-Marin" },
  { code: "ST", dial: "239", en: "São Tomé & Príncipe", fr: "Sao Tomé-et-Principe" },
  { code: "SA", dial: "966", en: "Saudi Arabia", fr: "Arabie saoudite" },
  { code: "SN", dial: "221", en: "Senegal", fr: "Sénégal" },
  { code: "RS", dial: "381", en: "Serbia", fr: "Serbie" },
  { code: "SC", dial: "248", en: "Seychelles", fr: "Seychelles" },
  { code: "SL", dial: "232", en: "Sierra Leone", fr: "Sierra Leone" },
  { code: "SG", dial: "65", en: "Singapore", fr: "Singapour" },
  { code: "SX", dial: "1", en: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)" },
  { code: "SK", dial: "421", en: "Slovakia", fr: "Slovaquie" },
  { code: "SI", dial: "386", en: "Slovenia", fr: "Slovénie" },
  { code: "SB", dial: "677", en: "Solomon Islands", fr: "Îles Salomon" },
  { code: "SO", dial: "252", en: "Somalia", fr: "Somalie" },
  { code: "ZA", dial: "27", en: "South Africa", fr: "Afrique du Sud" },
  { code: "KR", dial: "82", en: "South Korea", fr: "Corée du Sud" },
  { code: "SS", dial: "211", en: "South Sudan", fr: "Soudan du Sud" },
  { code: "ES", dial: "34", en: "Spain", fr: "Espagne" },
  { code: "LK", dial: "94", en: "Sri Lanka", fr: "Sri Lanka" },
  { code: "BL", dial: "590", en: "St. Barthélemy", fr: "Saint-Barthélemy" },
  { code: "SH", dial: "290", en: "St. Helena", fr: "Sainte-Hélène" },
  { code: "KN", dial: "1", en: "St. Kitts & Nevis", fr: "Saint-Christophe-et-Niévès" },
  { code: "LC", dial: "1", en: "St. Lucia", fr: "Sainte-Lucie" },
  { code: "MF", dial: "590", en: "St. Martin", fr: "Saint-Martin" },
  { code: "PM", dial: "508", en: "St. Pierre & Miquelon", fr: "Saint-Pierre-et-Miquelon" },
  { code: "VC", dial: "1", en: "St. Vincent & Grenadines", fr: "Saint-Vincent-et-les Grenadines" },
  { code: "SD", dial: "249", en: "Sudan", fr: "Soudan" },
  { code: "SR", dial: "597", en: "Suriname", fr: "Suriname" },
  { code: "SJ", dial: "47", en: "Svalbard & Jan Mayen", fr: "Svalbard et Jan Mayen" },
  { code: "SE", dial: "46", en: "Sweden", fr: "Suède" },
  { code: "CH", dial: "41", en: "Switzerland", fr: "Suisse" },
  { code: "SY", dial: "963", en: "Syria", fr: "Syrie" },
  { code: "TW", dial: "886", en: "Taiwan", fr: "Taïwan" },
  { code: "TJ", dial: "992", en: "Tajikistan", fr: "Tadjikistan" },
  { code: "TZ", dial: "255", en: "Tanzania", fr: "Tanzanie" },
  { code: "TH", dial: "66", en: "Thailand", fr: "Thaïlande" },
  { code: "TL", dial: "670", en: "Timor-Leste", fr: "Timor oriental" },
  { code: "TG", dial: "228", en: "Togo", fr: "Togo" },
  { code: "TK", dial: "690", en: "Tokelau", fr: "Tokelau" },
  { code: "TO", dial: "676", en: "Tonga", fr: "Tonga" },
  { code: "TT", dial: "1", en: "Trinidad & Tobago", fr: "Trinité-et-Tobago" },
  { code: "TA", dial: "290", en: "Tristan da Cunha", fr: "Tristan da Cunha" },
  { code: "TN", dial: "216", en: "Tunisia", fr: "Tunisie" },
  { code: "TR", dial: "90", en: "Türkiye", fr: "Turquie" },
  { code: "TM", dial: "993", en: "Turkmenistan", fr: "Turkménistan" },
  { code: "TC", dial: "1", en: "Turks & Caicos Islands", fr: "Îles Turques-et-Caïques" },
  { code: "TV", dial: "688", en: "Tuvalu", fr: "Tuvalu" },
  { code: "VI", dial: "1", en: "U.S. Virgin Islands", fr: "Îles Vierges des États-Unis" },
  { code: "UG", dial: "256", en: "Uganda", fr: "Ouganda" },
  { code: "UA", dial: "380", en: "Ukraine", fr: "Ukraine" },
  { code: "AE", dial: "971", en: "United Arab Emirates", fr: "Émirats arabes unis" },
  { code: "GB", dial: "44", en: "United Kingdom", fr: "Royaume-Uni" },
  { code: "US", dial: "1", en: "United States", fr: "États-Unis" },
  { code: "UY", dial: "598", en: "Uruguay", fr: "Uruguay" },
  { code: "UZ", dial: "998", en: "Uzbekistan", fr: "Ouzbékistan" },
  { code: "VU", dial: "678", en: "Vanuatu", fr: "Vanuatu" },
  { code: "VA", dial: "39", en: "Vatican City", fr: "État de la Cité du Vatican" },
  { code: "VE", dial: "58", en: "Venezuela", fr: "Venezuela" },
  { code: "VN", dial: "84", en: "Vietnam", fr: "Viêt Nam" },
  { code: "WF", dial: "681", en: "Wallis & Futuna", fr: "Wallis-et-Futuna" },
  { code: "EH", dial: "212", en: "Western Sahara", fr: "Sahara occidental" },
  { code: "YE", dial: "967", en: "Yemen", fr: "Yémen" },
  { code: "ZM", dial: "260", en: "Zambia", fr: "Zambie" },
  { code: "ZW", dial: "263", en: "Zimbabwe", fr: "Zimbabwe" },
];

/**
 * ISO codes in French alphabetical order. French names diverge enough from
 * English ("Germany" vs "Allemagne") that reusing the English ordering would
 * scatter the list for French readers. Pre-computed rather than sorted at
 * runtime so the option order cannot differ between server and client.
 */
export const FR_ORDER: string[] = [
  "AF", "ZA", "AL", "DZ", "DE", "AD", "AO", "AI", "AG", "SA", "AR", "AM",
  "AW", "AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BE", "BZ", "BJ", "BM",
  "BT", "BY", "BO", "BA", "BW", "BR", "BN", "BG", "BF", "BI", "KH", "CM",
  "CA", "CV", "CL", "CN", "CY", "CO", "KM", "CG", "CD", "KP", "KR", "CR",
  "CI", "HR", "CU", "CW", "DK", "DJ", "DM", "EG", "AE", "EC", "ER", "ES",
  "EE", "SZ", "VA", "US", "ET", "FJ", "FI", "FR", "GA", "GM", "GE", "GH",
  "GI", "GR", "GD", "GL", "GP", "GU", "GT", "GG", "GN", "GQ", "GW", "GY",
  "GF", "HT", "HN", "HU", "CX", "AC", "IM", "NF", "AX", "KY", "CC", "CK",
  "FO", "FK", "MP", "MH", "SB", "TC", "VG", "VI", "IN", "ID", "IQ", "IR",
  "IE", "IS", "IL", "IT", "JM", "JP", "JE", "JO", "KZ", "KE", "KG", "KI",
  "XK", "KW", "RE", "LA", "LS", "LV", "LB", "LR", "LY", "LI", "LT", "LU",
  "MK", "MG", "MY", "MW", "MV", "ML", "MT", "MA", "MQ", "MU", "MR", "YT",
  "MX", "FM", "MD", "MC", "MN", "ME", "MS", "MZ", "MM", "NA", "NR", "NP",
  "NI", "NE", "NG", "NU", "NO", "NC", "NZ", "OM", "UG", "UZ", "PK", "PW",
  "PA", "PG", "PY", "NL", "BQ", "PE", "PH", "PL", "PF", "PR", "PT", "QA",
  "HK", "MO", "CF", "DO", "RO", "GB", "RU", "RW", "EH", "BL", "KN", "SM",
  "MF", "SX", "PM", "VC", "SH", "LC", "SV", "WS", "AS", "ST", "SN", "RS",
  "SC", "SL", "SG", "SK", "SI", "SO", "SD", "SS", "LK", "SE", "CH", "SR",
  "SJ", "SY", "TJ", "TW", "TZ", "TD", "CZ", "IO", "PS", "TH", "TL", "TG",
  "TK", "TO", "TT", "TA", "TN", "TM", "TR", "TV", "UA", "UY", "VU", "VE",
  "VN", "WF", "YE", "ZM", "ZW",
];
