import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { routing, type Locale } from "@/i18n/routing";
import { Navbar } from "@/components/layout/Navbar";
import { MobileNav } from "@/components/layout/MobileNav";
import { Footer } from "@/components/layout/Footer";
import "../globals.css";
import "@/styles/_fonts.scss";
import "@/styles/_base.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale} className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <MobileNav />
          <main>{children}</main>
          <Footer />
          {process.env.NODE_ENV === "development" && (
            <>
              <LocalizationDebuggerLoader />
              <DesignGridOverlayLoader />
            </>
          )}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

async function LocalizationDebuggerLoader() {
  const { LocalizationDebugger } = await import(
    "@/components/dev/LocalizationDebugger"
  );
  return <LocalizationDebugger />;
}

async function DesignGridOverlayLoader() {
  const { DesignGridOverlay } = await import(
    "@/components/dev/DesignGridOverlay"
  );
  return <DesignGridOverlay />;
}
